### ISSUE TITLE
ReferenceError: __dirname is not defined | In epsilon-python.js

### ISSUE THREAD

**Issue by Xibitol** [Omega-Numworks/Omega-IDE#4]
**Hello, good evening,**

Since a few days I've been trying to compile your program (Omega-Ide) for my personal use and especially offline. For this I will: Modify the "LocalStorageConnector.js" file to put a file-based backup system on my computer.

Unfortunately when I launch the program an error appears in the Omega simulator window:
```
ReferenceError: __dirname is not defined

(anonymous function)
http://localhost:3000/epsilon-python.js:9:1367
```
I first checked where it came from and I also FULLY indented the first 700 lines of the file correctly. After that I discovered that the variable was never created. I would like to know where the problem comes from and how to fix it because it seems to be fixed on your website. 

**Thank you in advance for your answer.**

**Comment by M4xi1m3** [comment]
This is due to the fact that te simulator thinks its executed on node.js (gotta love emscripten). I'll make a patch soon.

**Comment by Xibitol** [comment]
Okay, when do you think you'll fix the problem? And if, when I run the program under test, there is an error on the webpack that appears on my browser (On localhost:3000) :

```
Uncaught ReferenceError: require is not defined
    at Object.events (external "events":1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object../node_modules/webpack/hot/emitter.js (emitter.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object../node_modules/webpack/hot/dev-server.js (dev-server.js:50)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (omega.ide.sass?954b:45)
```
should it be taken into consideration or is it part of the same problem?

**Comment by Xibitol** [comment]
**Are you here ?** @M4xi1m3 I need help after the first november if possible
**Thanks**
