### ISSUE TITLE
How to enable electron on your app

### ISSUE THREAD

**Issue by Xibitol** [Omega-Numworks/Omega-IDE#5]
**Hello, good morning,**

I have, since a few days, finished creating my recording system via files. Now, I would like to know how to launch your application and make it work on electron. I have already worked with electron several times but I don't know how several files can be launched: `start.js`, `start-react.js` and maybe others. I would like to know how to proceed just for create an electron app or if react already has a windows application creation system.

**Thank you in advance for your answer.**

**Comment by M4xi1m3** [comment]
The IDE isn't using electron. It's using nw.js. You can just run it by doing `npm install` then `npm start`

**Comment by Xibitol** [comment]
Yes, I used this to test my modifications but I would like to know if in `nw.js` there is a way to compile the code and get it with a `.exe`.

**Comment by Xibitol** [comment]
Finaly, I don't finded the solution for this. But I create a batch file to launch the program with this code : 
```batch
@echo off
title Omega Ide Launcher
mode con cols=57 lines=10
color 08

echo ---------------------------------------------------------
echo -----         Please don't close this window        -----
echo ---------------------------------------------------------

cd omega-ide-master
npm run start

```
If you want use this, just modify the relative path `cd`.
It work nicely, Thank you when even
