### ISSUE TITLE
[react-monaco-editor] Syntax highlighting

### ISSUE THREAD

**Issue by Xibitol** [Omega-Numworks/Omega-IDE#6]
**Hello,** hello, hello
It's me, yes, for the third time.

Now, Monaco editor not working, it just display a page with my text but no colour present. This image argument my problem.
I have searched to fix it on internet but your code is normal and I don't find where the problem coming.

![image](https://user-images.githubusercontent.com/47575082/98733680-29a02500-23a1-11eb-9fae-6a2dbf5171e3.png)

What is the problem and how I can fix this ? 

**Thank advance for your answer.**

**Comment by M4xi1m3** [comment]
This is a known issue I've been trying to fix for weeks. Our code is, in fact, not normal, as we can't use react rewired with nwjs (because it doesn't exist), so for now there is no syntax highlight on nwjs.

**Comment by Xibitol** [comment]
Ok ok, I doesn't thought about this. Good luck for fix this. Just, you knowing where the problem coming or it's still mystery ?

**Comment by M4xi1m3** [comment]
Fixed recently by ejecting and editing webpack config (yes I'm sad for ejecting too). Thank you for your issue.

**Comment by LeGmask** [comment]
W8 hmm overides config isn't possible ?
Since ejecting is nahhh...

**Comment by M4xi1m3** [comment]
Sadly no, I've been trying, a lot, and couldn't find. This only impacts the nwjs version, not the website, so that's not so bad, but yeah it sucks to have to eject to do that. If you can find a mix between react-app-rewired and nwjs, I'll try doing what I can with it tho.
